### ISSUE TITLE
A question about published model

### ISSUE THREAD

**Issue by wpstmxhs** [ymgaq/AQ#113]
Thank you for publishing the source code and model of GLOBIS-AQZ publicly.

I remember the times when GLOBIS-AQZ joined the Computer Go competitions.
On April of the last year, GLOBIS-AQZ joined a competition and that competition was held in Chinese Rules.
After a few months passed, on August of the last year, GLOBIS-AQZ joined another competition and that competition was held in Japanese Rules,

I also remember that GLOBIS-AQZ in the second competition seems stronger than the first one.
I just found that you published two different models, namely model_cn and model_jp.
It seems GLOBIS-AQZ is using different models depending on the game rule.

Can you explain clearly about these two models?
Thanks.

**Comment by ymgaq** [comment]
Thank you for posting the first issue of the new version.

As for the attached network files, as you might guess, they are different between the Japanese and Chinese rules. The Japanese rules are from last December's tournament. The network of Chinese rules is what made it relearn and additional learning for the Chinese rule.

I don't think it's stronger than other published AIs, because it's not sufficiently learned in the Chinese rule, but we preferred to be as similar opening strategies as possible with different rules.

**Comment by wpstmxhs** [comment]
@ymgaq Now I just noticed I confused the times of when two competitions were held.
So I have to correct. On April of the last year, GLOBIS-AQZ was officially presented.
GLOBIS-AQZ joined the competitions held on August and December of the last year.
Thank you for your explanation.
You stated that the published model of Chinese rule is what AQZ team re-trained later.
Then, Is the new model of Chinese rule stronger than the model used on last August?

**Comment by ymgaq** [comment]
1,2. We don't know the exact rating difference because we didn't take direct rating measurements. (I'm estimating the relearned version will win against the last August version, but not sure.)

3. As you point out, we can't directly compare the two networks; the 90% is just a comparison under the Japanese rule. In the case of self match, it is very often a half point game, so it is advantageous to conform to the rules.

**Comment by wpstmxhs** [comment]
@ymgaq 親切なご返事本当に有難うございます！
