### ISSUE TITLE
Compile for Mac OS

### ISSUE THREAD

**Issue by zhurak** [ymgaq/AQ#13]
Did anyone try to compile AQ on Max OS?

**Comment by ymgaq** [comment]
I have no MacOS machine.
However, it may be possible to build using [bazel](https://docs.bazel.build/versions/master/install-os-x.html) or other compilers.
When using bazel, try options of '-c opt' and '--config=cuda'.

**Comment by y-ich** [comment]
FYI
I ported AQ for macOS without GPU.
https://github.com/y-ich/AQ/tree/mac_cpu

1. You need to change BUILD for the latest tensorflow(r1.3)
1. You need to replace std::thread with boost::thread since std::thread on macOS has small, fixed-size stack(512kB).

I am not quite sure about compiing the latest version of tensorflow with GPU. You may or not need to install old clang for nvcc.
Cheers.

**Comment by ymgaq** [comment]
@y-ich Thank you for sharing useful information on build on MacOS.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
