### ISSUE TITLE
AQ (win) always resign if run in the middle of the game

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [ymgaq/AQ#19]
I've tried to analyze game with AQ. To do so I did next:
- open game with Sabaki viewer with support GTP
- scrool to position
- use attach engine
But after thinking AQ just resign. In any position when game is even. 
Tried default config and with japanese rules.
Tried -never resign =on but AQ still resign.

When I use Sabaki to play against AQ - it works fine (well haven't tested deep yet but at brief look it works). So assume may be the issue with loading existing game

Attached logs, game and screenshot. Added txt to sgf files -because github doesn't support sgf.

![599 15-oct-17 13 56](https://user-images.githubusercontent.com/7886823/31584215-cefb6a82-b1b2-11e7-8943-f8fecbbe9c20.jpg)
[1.txt](https://github.com/ymgaq/AQ/files/1385369/1.txt)
[game_1.sgf.txt](https://github.com/ymgaq/AQ/files/1385370/game_1.sgf.txt)
[1.sgf.txt](https://github.com/ymgaq/AQ/files/1385371/1.sgf.txt)

**Comment by ymgaq** [comment]
This is due to the difference between AQ and Sabaki's reading style of SGF file.
I tried Sabaki now, and found it seems to send 'play W' or 'play B' so that stones are placed from the top left to the bottom right.
However, since AQ is supposed to proceed alternately with 'Play W' -> 'play B' -> 'Play W', partly white and black stones are exchanged.

I will modify it to accommodate such style.

**Comment by ymgaq** [comment]
The modified version (v2.0.3.1) is [released](https://github.com/ymgaq/AQ/releases).

**Comment by aTan-aka-Xellos** [comment]
@ymgaq that was incredibly fast! Thank you! Will test soon.
