### ISSUE TITLE
AQ commit suicide during filling dame

### ISSUE THREAD

**Issue by aTan-aka-Xellos** [ymgaq/AQ#22]
In last game during test found that AQ commit suicide during filling dame.
Please check last 2 moves in next game:
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2017/10/16/297028.sgf

If any kind of such situations (suicide/missed ladder/etc.) will be found in future - are you interested to have this issues to be reported?

**Comment by ymgaq** [comment]
I think AQ noticed that it had no chance to win, so it choose a move according to rollout rates. It is not important whether it is suicide or not because it would lose by 1.5 point even if it did its best.

> If any kind of such situations (suicide/missed ladder/etc.) will be found in future - are you interested to have this issues to be reported?

I am grateful, but I do not need it, since I can not understand it at all (I'm only about 10k or 15k), and since most 'mistakes' reported are not easy to fix.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
