### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by elpanor** [ymgaq/AQ#28]
Thx for making great AI go program.

I have  some questions.

1. Is there a methods to extend tree search, or move count?
   If I raise up max_node_limit, is it effective?(and max node limit = 65537.  2^16=65536. What is +1's meaning?)

2. AQ use max about 10 Giga memory. Can I raise up memory usage?

3. What is AQ's maximum CPU thread counts?

3. Could u open AQ training methods or training tool in detail?

....... Sorry for silly question.

**Comment by ymgaq** [comment]
Good questions.

> Is there a methods to extend tree search, or move count?
> If I raise up max_node_limit, is it effective?(and max node limit = 65537. 2^16=65536. What is +1's meaning?)

It is effective. 
If you use a larger number of `node_limit`, AQ can extend thinking time (until the nodes table is full).

63357 is the closest prime number to 2 ^ 16.
Generally speaking, the size of Hash table is initialized as a power of two or a prime number. 

AQ adopts Zobrist hash and simple key generation (i.e. `BoardHash(b) % node_limit` ) , so I think that there is no difference in the frequency of hash collisions between them, but I am using the prime number just in case.

> AQ use max about 10 Giga memory. Can I raise up memory usage?

I will consider to add an option to change node size.

> What is AQ's maximum CPU thread counts?

Depends on the number of CPU cores and OS. 
If your CPU has 8 thread, you should set 8 (or 8 + gpu count, because thread count includes threads for GPU evaluation) as maximum.
I think 5 or 6 thread count per GPU is most efficient because AQ stops thinking while evaluation queue is full.

> Could u open AQ training methods or training tool in detail?

I will release the codes for training as soon as I finish organizing them, but it is too complicated because I'm trying new network or learning method every day.

**Comment by trainewbie** [comment]
You told above that you will consider to add an option to change node size.
When you add a changeable options, how about adding other options?
 : expand_cnt, Lamda, cp, policy_temp parameter. etc.

**Comment by Vargooo** [comment]
Hello, I love AQ, it's very very strong...
I use Sabaki to set up games against Leela, gnugo, etc.
My computer : Windows 10 i7-6700K (4gHz) 32GB     GTX1080

In aq_config.txt , I have :
-gpu count =1
-thread count =8
Is it correct with my hardware ?
Should I make other changes in aq_config.txt  ?
Thank you for your answer, and for this beautiful program.

**Comment by ymgaq** [comment]
@Vargooo I think it is better to set around 5 to `thread count` because CPU threads wait for the gpu thread if the evaluation queue is full. If you have 2 GPUs, 8 or more `thread count` works.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
