### ISSUE TITLE
Can't recognize Ko when attaching AQ to Sabaki in the middle of the game 

### ISSUE THREAD

**Issue by sunmier** [ymgaq/AQ#39]
When attaching AQ to Sabaki in the middle of the game, the order of the game is loaded differently from the actual one, so that AQ suggest "Ko postion" as in the picture.  (The last move is W to J10)
![1](https://user-images.githubusercontent.com/33387892/32412637-4be8476a-c241-11e7-91f3-b9eca4682232.jpg)

**Comment by ymgaq** [comment]
This is not due to AQ, it is the specification of Sabaki.
Sabaki places stones from the upper left to the lower right when telling stone information to the program. At this time, the Ko information is lost.

If you want to avoid this problem, you should use [GoGui](https://sourceforge.net/projects/gogui/) or other GUI softwares.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
