### ISSUE TITLE
Time control in AQ 2.1.1

### ISSUE THREAD

**Issue by Heiseikiseki** [ymgaq/AQ#62]
I found that AQ 2.1.1 is just follow the byoyomi for thinking. Even the First hand, it thinks so long. Is it able for AQ to control the time by it self? Like Zen7 even I set 30second it would think between 5s~30s.

**Comment by Heiseikiseki** [comment]
And Also I notice that AQ has 1 second more than byoyomi . For Example, If I set 5 second for byoyomi, it would spend 6 second. Baybe it's a delay between sabaki and the AQ or it's a bug?

**Comment by ymgaq** [comment]
AQ tries to use the given time effectively. If you like a shorter thinking time, change that setting as such. 

In the case of byoyomi only, since it does not take a margin, there is a possibility that it may be as much as 0.2 seconds longer than the setting. If it exceeds 1 second, it may be due to communication with the GUI software.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
