### ISSUE TITLE
Can you add a book.dat format opening book to AQ?

### ISSUE THREAD

**Issue by dochouse007** [ymgaq/AQ#66]
Can you add a book.dat format opening book to AQ? Like the walking method in AlphaGo Teaching Tool

**Comment by ymgaq** [comment]
AQ has its own [opening book format](https://github.com/ymgaq/AQ/blob/850bcff9b129ccfafa74e1a3a86fdb88de31471f/src/search.cpp#L162-181) but the current version does not include any opening books because several opening books I tried did not contribute to strength.

If you want to add opening book with other formats, please implement conversion method and send pull request.

**Comment by dochouse007** [comment]
I made a very strong book, is the book.dat format how to sent to you?

**Comment by ymgaq** [comment]
You don't need to send it. If you want to use it, please implement importing method for your opening book and send pull request.

**Comment by dochouse007** [comment]
What's the format of the opening book of AQ?  How can book.dat format be converted to the format required by AQ?

**Comment by ymgaq** [comment]
As I mentioned, the importing method of AQ's format is implemented [here](https://github.com/ymgaq/AQ/blob/850bcff9b129ccfafa74e1a3a86fdb88de31471f/src/search.cpp#L162-181). It is a binary file with total board count (4byte) , registered move count (4byte), board hash (8byte) and move (4byte). I don't know how to convert your file.

**Comment by dochouse007** [comment]
Maybe you can modify the AQ engine, let him start to support the.Bin format opening book, I think it might be able to improve AQ winrate.

**Comment by ymgaq** [comment]
Since AQ is open source software, anyone can improve it. If you think that it will become stronger in that way, please implement it and pull request.

**Comment by ymgaq** [comment]
This issue is closed due to lack of recent activity.
