### ISSUE TITLE
AQ misread Life/death

### ISSUE THREAD

**Issue by jillybob** [ymgaq/AQ#90]
AQ on Windows 10, running GTP. CPU i5-6500, GPU GTX 970 
+ Reproduction procedure: Play this game https://online-go.com/game/11949281

Winrate dropped from 52.4 to 2.1%, how can AQ not see H6? 

Output when H6 was played https://i.imgur.com/jPBqDAx.png

**Comment by hydrogenpi** [comment]
So ladder knowledge is hard coded in AQ?

**Comment by hydrogenpi** [comment]
AQ also lost two games to LZ that it otherwise would have won:

1)Making an "illegal" move when it was ahead, forfeiting the game and losing!
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/03/10/394118.sgf

2) Making a suicide move that lost the group in the down left corner that was already alive! 
http://www.yss-aya.com/cgos/viewer.cgi?19x19/SGF/2018/03/10/394010.sgf

**Comment by geovens** [comment]
For the second one (394010.sgf), I believe the bottom left was a seki if black didn't make a suicide move? I think that AQ is not good at seki. Only when a situation has degraded to the simplest seki situation (like only two inside liberties left) does AQ acknowledge the seki thanks to it beeing hard coded. Other than that AQ just consider itself dead because every move would result in death.

**Comment by ymgaq** [comment]
This issue mentions an older version, or hasn't been discussed in a long time, so we close it.
